---
title: Explorer for Endevor Release Notes
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/E4E-ReleaseNotes/
folder: che-7/extensions
summary:
---

[id="E4E-ReleaseNotes"]
= Explorer for Endevor Release Notes

:context: E4E-ReleaseNotes

#### Version 0.8.0
Version 0.8 was released on 1 August 2019 and includes the following features:

##### Explore Endevor Data Maps
- Explorer for Endevor lets you browse through Endevor data without any prior knowledge of the file paths being necessary

##### Create Filters Based on Your Searches
- Explorer for Endevor lets you create customer filters based on the searches you perform in the Map View

##### Customisable Filters
- Explorer for Endevor lets you create customisable filters for ease of browsing data sets.

#### Version 0.9.0
Version 0.9 was released on 19 September 2019 and includes the following features:

##### Advanced Create Filter function
- Experienced users can create custom filters without having to use Map View

##### Improved Host Creation process
- Streamlined process to create new Host connections

##### UX Enhancements

#### Version 0.9.1
Version 0.9.1 was released on 28 September 2019 and includes the following features:

##### Updated README

##### Updated License

#### Version 0.10.0
Version 0.10.0 was released on 25 June 2020 and includes the following features:
##### Updated README

##### Endevor Plug-in for Zowe CLI profile interoperability  
- Users can utilize their Endevor Plug-in for Zowe CLI profiles in Explorer for Endevor
- If a user has a default Endevor profile, it will be loaded automatically in the extension
- Users can also create a new Endevor profile from within the extension

##### Endevor Bridge for Git support deprecated
- Synchronized Git-Endevor mappings are no longer read and the Endevor configuration will not be imported 