---
title: Install Explorer for Endevor
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/E4E-InstallE4E/
folder: che-7/extensions
summary:
---

[id="E4E-InstallE4E"]
= Install Explorer for Endevor

:context: E4E-InstallE4E

Explorer for Endevor lets you view and edit Endevor data using a user-friendly, intuitive modern interface, such as Visual Studio Code, or Eclipse Che.

Explorer for Endevor allows you to create customized views and filters for Endevor data, enabling you to identify and retrieve specific elements, using a modern front-end Endevor interface

## Install Explorer for Endevor for Eclipse Che

Explorer for Endevor can be installed as part of the Eclipse Che4z basic stack.

#### Prerequisites
Eclipse Che 7.3 on Kubernetes

#### Procedure
. Log in to Eclipse Che.

. In a web browser, load the following URL:
    `https://<CHE_HOST>/f?url=https://github.com/eclipse/che-che4z/raw/1.0.0/mainframe-basic-stack.yaml`

    - `https://<CHE_HOST>` specifies the Che Server URL, for example: `https://my-che-server.com.`

    - `/f?url=` links the Che Server URL to the Eclipse Che4z basic stack URL.

    - `https://github.com/eclipse/che-che4z/raw/1.0.0/mainframe-basic-stack.yaml` is the Eclipse Che4z basic stack URL.

. Press Enter and wait for the workspace to initialize.

. A workspace is created with Eclipse Che4z extensions available.

## Install Explorer for Endevor for Visual Studio Code

Explorer for Endevor for Visual Studio Code (VSC) lets you view and edit Endevor data using a user-friendly, intuitive modern interface.

Explorer for Endevor allows you to create customized views and filters for Endevor data, enabling you to identify and retrieve specific elements, using a modern front-end Endevor interface

### Prerequisites
- Visual Studio Code v1.32.0 installed
- CA Mainframe credentials
- Endevor version 18.0.12 or higher with Web Services enabled.
  - For more information, see Enable Web Services
  - Ensure latest maintenance upgrade PTF SO08898 is included.
- Rest API complete with maintenance upgrade PTFs SO05688, SO05689, SO07195, SO07084, and SO07085
- Endevor credentials
- Endevor data source

#### Follow these steps:

1. Open Visual Studio Code.
2. Navigate to the Extensions Marketplace and enter "Explorer for Endevor" in the search field.
3. Click Install under the Extension description.
- The Explorer for Endevor tab displays under the VSC Marketplace icon.
4. Click File on the top taskbar, then click Open Workspace on the drop down menu.
5. Define the location where you want to save any retrieved elements.
    
The location contents are now shown in the Explorer for Endevor Data tab.

#### Tip:
Restart your chosen IDE after the install process completes.
This ensures that everything is configured correctly prior to using Explorer for Endevor for the first time.

You have successfully installed the Explorer for Endevor extension for Visual Studio Code
