name: GitHub Actions Demo

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      BLACKDUCK_API_TOKEN: ${{ secrets.E4E_BLACKDUCK_TOKEN }}
      PROJECT_NAME: explorer-for-endevor

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        # order operating systems from best to worst
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Package
        run: npx vsce package
        run: mv $PROJECT_NAME.vsix $PROJECT_NAME_latest.vsix
