name: E4E CI Workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  PROJECT_NAME: explorer-for-endevor
jobs:
  build-test-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Audit
        run: yarn audit --level high || exit 0
        id: audit
      - name: Lint
        run: yarn lint
      - name: Build E4E
        run: yarn workspace ${{ env.PROJECT_NAME }} build:dev
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        id: tests
        with:
          run: yarn test
      - name: Package VSIX & Upload Artifact
        run: |
          yarn copy-into-build-context
          yarn workspace ${{ env.PROJECT_NAME }} package
      - uses: actions/upload-artifact@v2
        env:
          VSIX_PATH: packages/${{ env.PROJECT_NAME }}/vsce/*.vsix
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.VSIX_PATH }}
