name: E4E CI Workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  PROJECT_NAME: explorer-for-endevor
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      # Continue to run tests on the other systems if one fails
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get E4E package version
        env:
          ENDEVOR_VERSION_PATH: packages/${{env.PROJECT_NAME}}/package.json
        id: npm-version
        uses: nyaa8/package-version@v1.0.3
        with:
          path: ${{ env.ENDEVOR_VERSION_PATH }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Audit
        id: audit
        continue-on-error: true
        run: yarn audit
      - name: Lint
        run: yarn lint
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test

  create-artifact:
    runs-on: ${{ matrix.os }}
    if: jobs.build-and-test.steps.audit.outputs.exit_code < 7
    steps:
      - name: Build E4E
        run: yarn build
      - name: Package VSIX & Upload Artifact
        run: yarn workspace ${{ env.PROJECT_NAME }} package
      - uses: actions/upload-artifact@v2
        env:
          VSIX_PATH: packages/${{ env.PROJECT_NAME }}/vsce/*.vsix
        with:
          name: ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}
          path: ${{ env.VSIX_PATH }}
