name: E4E Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      PROJECT_NAME: explorer-for-endevor

    strategy:
      # Continue to run tests on the other systems if one fails
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # TODO: Add back windows-latest when tests are fixed
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Audit
        id: audit
        continue-on-error: true
        run: yarn audit

      - name: Lint
        run: yarn lint

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test

      - name: Build package
        if: steps.audit.outputs.exit_code < 7
        run: yarn build

      - name: Package VSIX & Upload Artifact
        if: steps.audit.outputs.exit_code < 7
        run: yarn workspace ${{ env.PROJECT_NAME }} package
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME }}
          path: packages/${{ env.PROJECT_NAME }}/vsce/*.vsix

      - name: Publish to ARtifactory
        uses = "retgits/actions/jfrog-cli@master"
        secrets = ["USER", "PASSWORD", "URL"]
        args = ["upload ${{ env.PROJECT_NAME }}.vsix eclipse/explorer-for-endevor/ --build-name=${{ env.PROJECT_NAME }}"]
        env = {
          CRED = "username"
        }

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        id: publishToOpenVSX
        with:
          extensionFile: packages/${{ env.PROJECT_NAME }}/vsce/*.vsix
          pat: ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          packagePath: ''